# Generated by Django 3.0.4 on 2020-04-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200408_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='failedstudents',
        ),
        migrations.RemoveField(
            model_name='result',
            name='passedstudent',
        ),
        migrations.RemoveField(
            model_name='result',
            name='purchaeddatetime',
        ),
        migrations.AddField(
            model_name='result',
            name='FailedNames',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='StudentInformation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='updated_models',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='owner',
            field=models.CharField(max_length=200),
        ),
    ]
