# Generated by Django 3.0.4 on 2020-04-18 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200418_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='orders',
            field=models.FileField(null=True, upload_to='userfiles/'),
        ),
        migrations.DeleteModel(
            name='UserOrders',
        ),
    ]
